insert into Branches (BID, BNAME, BADD, BMAN) values (10, 'Ash Shāmīyah', '82684 Randy Park', 6);
insert into Branches (BID, BNAME, BADD, BMAN) values (1, 'Tampocon', '3 Stephen Trail', 10);
insert into Branches (BID, BNAME, BADD, BMAN) values (9, 'Chaem Luang', '20617 Schmedeman Court', 6);
insert into Branches (BID, BNAME, BADD, BMAN) values (1, 'Khinjān', '9094 Carioca Road', 6);
insert into Branches (BID, BNAME, BADD, BMAN) values (2, 'Brétigny-sur-Orge', '7 Hanover Point', 8);
insert into Branches (BID, BNAME, BADD, BMAN) values (2, 'Xidoupu', '14 Cambridge Avenue', 5);
insert into Branches (BID, BNAME, BADD, BMAN) values (2, 'Moyamba', '8 Hooker Plaza', 10);
insert into Branches (BID, BNAME, BADD, BMAN) values (1, 'Cermee', '45 Moose Terrace', 8);
insert into Branches (BID, BNAME, BADD, BMAN) values (10, 'Smyshlyayevka', '491 Columbus Way', 2);
insert into Branches (BID, BNAME, BADD, BMAN) values (1, 'Turets-Bayary', '05986 Mariners Cove Alley', 10);
