insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (81, 'Mint - Fresh', 'Laundry - Bag Cloth', 68, 'LENGTH', 26, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (70, 'Pork - Back, Long Cut, Boneless', 'Carroway Seed', 11, 'AREA', 47, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (44, 'Tray - Foam, Square 4 - S', 'Scallops - 10/20', 28, 'AREA', 20, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (1, 'Lemonade - Island Tea, 591 Ml', 'Wine - Niagara,vqa Reisling', 76, 'LITRE', 89, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (87, 'Calypso - Black Cherry Lemonade', 'Nut - Pumpkin Seeds', 49, 'LITRE', 17, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (98, 'Tart Shells - Sweet, 3', 'Wine - Chardonnay Mondavi', 78, 'AREA', 39, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (58, 'Eggplant - Baby', 'Dried Figs', 45, 'LENGTH', 92, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (79, 'Skewers - Bamboo', 'Plasticspoonblack', 53, 'LENGTH', 49, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (84, 'Orange - Canned, Mandarin', 'Bread Foccacia Whole', 90, 'AREA', 81, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (78, 'Milk - Skim', 'Soup - French Onion', 19, 'AREA', 14, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (15, 'Wine - Fat Bastard Merlot', 'Wonton Wrappers', 18, 'AREA', 18, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (88, 'Crab - Back Fin Meat, Canned', 'Lamb - Loin, Trimmed, Boneless', 69, 'LENGTH', 91, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (69, 'Cheese - Boursin, Garlic / Herbs', 'Chicken - Whole Roasting', 69, 'KG', 19, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (37, 'Soup - Knorr, Ministrone', 'Butter - Salted, Micro', 83, 'AREA', 86, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (40, 'Beer - Sleeman Fine Porter', 'Lettuce - Green Leaf', 84, 'LENGTH', 52, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (7, 'Rum - Light, Captain Morgan', 'Beef - Tongue, Fresh', 74, 'LENGTH', 21, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (1, 'Bread Crumbs - Panko', 'Star Anise, Whole', 26, 'LITRE', 90, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (45, 'Muffins - Assorted', 'Ecolab - Hobart Washarm End Cap', 37, 'AREA', 6, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (99, 'Lobak', 'Herb Du Provence - Primerba', 99, 'AREA', 99, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (63, 'Truffle Shells - White Chocolate', 'Bagels Poppyseed', 81, 'KG', 24, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (33, 'Cabbage - Nappa', 'Clams - Canned', 84, 'KG', 45, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (95, 'Sauce - Plum', 'Beef - Eye Of Round', 93, 'LENGTH', 55, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (52, 'Pastrami', 'Wine - Carmenere Casillero Del', 45, 'LENGTH', 91, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (87, 'Sea Bass - Fillets', 'Squid - U - 10 Thailand', 98, 'AREA', 77, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (98, 'Sole - Iqf', 'Cheese - Marble', 2, 'LENGTH', 67, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (39, 'Cod - Fillets', 'Egg Patty Fried', 80, 'AREA', 68, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (92, 'Ham - Smoked, Bone - In', 'Mayonnaise', 25, 'LITRE', 84, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (87, 'Syrup - Monin, Swiss Choclate', 'Beef - Bresaola', 73, 'LITRE', 50, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (100, 'Lamb - Loin Chops', 'Apron', 23, 'AREA', 16, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (6, 'Wine - Sake', 'Cinnamon Rolls', 43, 'LENGTH', 6, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (28, 'Mountain Dew', 'Muffin Batt - Choc Chk', 43, 'AREA', 6, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (77, 'Molasses - Fancy', 'Garlic - Primerba, Paste', 23, 'LENGTH', 4, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (75, 'Yogurt - Strawberry, 175 Gr', 'Cheese - Perron Cheddar', 69, 'LENGTH', 27, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (30, 'Anchovy In Oil', 'Napkin - Beverage 1 Ply', 19, 'KG', 59, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (29, 'Olives - Stuffed', 'Cheese - Taleggio D.o.p.', 34, 'LENGTH', 57, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (97, 'Carrots - Jumbo', 'Cheese - Comtomme', 84, 'LENGTH', 43, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (10, 'Kaffir Lime Leaves', 'Ranchero - Primerba, Paste', 52, 'LENGTH', 61, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (13, 'Milk Powder', 'Monkfish Fresh - Skin Off', 20, 'AREA', 8, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (13, 'Muffin Mix - Raisin Bran', 'Wine - Red, Gallo, Merlot', 52, 'AREA', 61, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (78, 'Ketchup - Tomato', 'Nut - Pine Nuts, Whole', 84, 'LITRE', 67, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (86, 'Skewers - Bamboo', 'Mix - Cocktail Ice Cream', 75, 'KG', 75, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (35, 'Dill Weed - Fresh', 'Water - Aquafina Vitamin', 16, 'LENGTH', 3, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (55, 'Sauce - Black Current, Dry Mix', 'Rice - Aborio', 44, 'KG', 66, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (20, 'Marzipan 50/50', 'Lamb Shoulder Boneless Nz', 98, 'LENGTH', 3, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (5, 'Chicken - Tenderloin', 'Sugar - Cubes', 68, 'AREA', 86, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (57, 'Spice - Peppercorn Melange', 'Garlic - Elephant', 58, 'KG', 15, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (34, 'Tofu - Soft', 'Mackerel Whole Fresh', 33, 'LENGTH', 44, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (89, 'Island Oasis - Pina Colada', 'Wine - Stoneliegh Sauvignon', 53, 'LITRE', 2, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (58, 'Bread - Raisin', 'Pickerel - Fillets', 7, 'AREA', 25, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (98, 'Truffle - Whole Black Peeled', 'Fudge - Chocolate Fudge', 50, 'LENGTH', 7, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (37, 'Gatorade - Orange', 'Lettuce - Spring Mix', 68, 'AREA', 15, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (10, 'Spice - Montreal Steak Spice', 'Fudge - Chocolate Fudge', 96, 'LENGTH', 35, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (61, 'Barley - Pearl', 'Five Alive Citrus', 57, 'KG', 88, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (33, 'Pepper - Black, Ground', 'Chocolate - Semi Sweet, Calets', 1, 'LENGTH', 34, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (67, 'Tuna - Bluefin', 'Lamb - Leg, Diced', 76, 'LENGTH', 92, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (55, 'Chinese Foods - Thick Noodles', 'Wine - Placido Pinot Grigo', 47, 'KG', 33, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (73, 'Cod - Black Whole Fillet', 'Artichokes - Jerusalem', 97, 'LENGTH', 98, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (35, 'Trout Rainbow Whole', 'Beef - Short Loin', 22, 'AREA', 73, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (41, 'Food Colouring - Pink', 'Scampi Tail', 89, 'AREA', 71, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (79, 'Sprouts - Baby Pea Tendrils', 'Chocolate - Mi - Amere Semi', 74, 'LITRE', 72, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (7, 'Buttons', 'Flour - Semolina', 90, 'AREA', 59, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (13, 'The Pop Shoppe - Black Cherry', 'Wine - Rosso Toscano Igt', 78, 'LITRE', 33, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (34, 'Snapple Raspberry Tea', 'Apple - Northern Spy', 17, 'LITRE', 37, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (17, 'Barramundi', 'Vector Energy Bar', 15, 'LITRE', 58, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (54, 'Mushroom - Trumpet, Dry', 'Alize Gold Passion', 49, 'LITRE', 75, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (45, 'Napkin - Cocktail,beige 2 - Ply', 'Lid Coffeecup 12oz D9542b', 91, 'KG', 10, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (63, 'Swordfish Loin Portions', 'Lamb - Racks, Frenched', 87, 'AREA', 98, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (28, 'Trout - Rainbow, Fresh', 'Daikon Radish', 30, 'LENGTH', 76, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (82, 'Cheese - Havarti, Roasted Garlic', 'Passion Fruit', 2, 'LENGTH', 84, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (70, 'Bay Leaf Ground', 'The Pop Shoppe - Cream Soda', 37, 'KG', 67, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (27, 'Sugar - Invert', 'Tea - Earl Grey', 9, 'KG', 35, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (19, 'Marjoram - Fresh', 'Huck White Towels', 32, 'KG', 52, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (92, 'Truffle - Whole Black Peeled', 'Pork - Liver', 24, 'LENGTH', 28, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (29, 'Cheese - Augre Des Champs', 'Ham - Smoked, Bone - In', 8, 'AREA', 19, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (40, 'Pepper - Jalapeno', 'Butter - Salted, Micro', 69, 'AREA', 26, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (14, 'Glass - Wine, Plastic, Clear 5 Oz', 'Glass - Juice Clear 5oz 55005', 41, 'LENGTH', 1, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (15, 'Chocolate - Pistoles, Lactee, Milk', 'Wine - Masi Valpolocell', 51, 'LENGTH', 19, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (15, 'Chocolate Bar - Coffee Crisp', 'Tea - Jasmin Green', 26, 'KG', 92, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (64, 'Nut - Almond, Blanched, Whole', 'Ice Cream Bar - Drumstick', 89, 'LENGTH', 50, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (54, 'Sage - Ground', 'Bacardi Breezer - Strawberry', 22, 'LENGTH', 93, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (63, 'Bread Base - Italian', 'Mushroom - Crimini', 25, 'KG', 83, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (46, 'Melon - Watermelon Yellow', 'Sprouts - Onion', 65, 'KG', 90, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (52, 'Dip - Tapenade', 'Eggroll', 70, 'LENGTH', 95, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (24, 'Spaghetti Squash', 'Wine - Rosso Del Veronese Igt', 71, 'LENGTH', 98, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (95, 'Lemon Tarts', 'Tarragon - Fresh', 14, 'AREA', 98, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (26, 'Asparagus - Green, Fresh', 'Coffee - Colombian, Portioned', 70, 'LITRE', 31, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (8, 'Jagermeister', 'Pork Salted Bellies', 92, 'LENGTH', 51, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (64, 'Wine - White, Pelee Island', 'Beef - Flank Steak', 49, 'AREA', 20, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (94, 'Kaffir Lime Leaves', 'Calypso - Black Cherry Lemonade', 26, 'LENGTH', 11, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (77, 'Pie Box - Cello Window 2.5', 'Tendrils - Baby Pea, Organic', 10, 'LENGTH', 50, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (12, 'Versatainer Nc - 888', 'Spice - Pepper Portions', 79, 'LENGTH', 37, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (60, 'Muffin Hinge - 211n', 'Slt - Individual Portions', 30, 'AREA', 44, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (13, 'Chocolate - Liqueur Cups With Foil', 'Croissants Thaw And Serve', 61, 'LITRE', 56, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (71, 'Mushroom - King Eryingii', 'Sauce Bbq Smokey', 92, 'LITRE', 56, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (36, 'Salmon - Atlantic, No Skin', 'Beer - Creemore', 24, 'AREA', 85, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (74, 'Fork - Plastic', 'Vinegar - Cider', 64, 'AREA', 81, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (3, 'Chocolate - Dark Callets', 'Bouillion - Fish', 27, 'LENGTH', 73, true);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (37, 'Squash - Pepper', 'Sprouts - Bean', 34, 'AREA', 87, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (8, 'Ecolab Silver Fusion', 'Beer - Sleemans Cream Ale', 91, 'AREA', 17, false);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (5, 'Ecolab - Mikroklene 4/4 L', 'Wine - Shiraz Wolf Blass Premium', 47, 'LENGTH', 42, true);
