insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (1, 'Bagel - Ched Chs Presliced', 'Rum - Coconut, Malibu', 14, 'AREA', 32, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (2, 'Pike - Frozen Fillet', 'Grapes - Black', 74, 'LENGTH', 53, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (3, 'Pasta - Spaghetti, Dry', 'Lemonade - Black Cherry, 591 Ml', 18, 'LENGTH', 41, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (4, 'Beef - Montreal Smoked Brisket', 'Tea - Orange Pekoe', 13, 'LENGTH', 26, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (5, 'Ice Cream - Chocolate', 'Soup - Campbells Mushroom', 4, 'LENGTH', 83, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (6, 'Lettuce - Sea / Sea Asparagus', 'Wine - Beaujolais Villages', 82, 'LENGTH', 8, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (7, 'Sauce - Rosee', 'Celery', 43, 'KG', 72, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (8, 'Salmon - Fillets', 'Chevere Logs', 20, 'LENGTH', 36, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (9, 'Bread Base - Goodhearth', 'Bread - English Muffin', 84, 'LENGTH', 96, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (10, 'Water - San Pellegrino', 'Rum - Cream, Amarula', 77, 'LITRE', 38, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (11, 'Plate - Foam, Bread And Butter', 'Appetizer - Mango Chevre', 63, 'LENGTH', 86, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (12, 'Celery', 'Wasabi Paste', 33, 'KG', 69, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (13, 'Beef - Top Sirloin - Aaa', 'Roe - White Fish', 81, 'LENGTH', 67, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (14, 'Coconut - Shredded, Unsweet', 'Wine - Remy Pannier Rose', 63, 'AREA', 13, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (15, 'Anchovy Paste - 56 G Tube', 'Stainless Steel Cleaner Vision', 76, 'LITRE', 80, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (16, 'Sausage - Liver', 'Pomello', 1, 'AREA', 45, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (17, 'Tortillas - Flour, 8', 'Soup - French Onion, Dry', 60, 'LENGTH', 40, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (18, 'Veal - Nuckle', 'Nut - Macadamia', 62, 'LENGTH', 17, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (19, 'Sauce - Marinara', 'Wine - Casillero Del Diablo', 90, 'KG', 85, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (20, 'Cheese - Colby', 'Clams - Canned', 42, 'AREA', 27, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (21, 'Beef - Kindney, Whole', 'Cup - 4oz Translucent', 52, 'KG', 40, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (22, 'Wine - Chateau Aqueria Tavel', 'Soup - Campbells, Beef Barley', 62, 'LITRE', 29, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (23, 'Sauce - Balsamic Viniagrette', 'Gatorade - Cool Blue Raspberry', 68, 'AREA', 91, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (24, 'Pork - Kidney', 'Carroway Seed', 48, 'KG', 96, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (25, 'Puree - Kiwi', 'Basil - Thai', 13, 'LENGTH', 57, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (26, 'Almonds Ground Blanched', 'Lid - Translucent, 3.5 And 6 Oz', 22, 'LITRE', 29, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (27, 'Artichokes - Jerusalem', 'Beer - Camerons Auburn', 36, 'KG', 29, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (28, 'Foil - Round Foil', 'Cattail Hearts', 40, 'LITRE', 21, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (29, 'Chicken Breast Halal', 'Milk - Chocolate 500ml', 71, 'AREA', 88, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (30, 'Strawberries', 'Bread - Bistro White', 3, 'AREA', 63, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (31, 'Snails - Large Canned', 'Cheese - Valancey', 6, 'LITRE', 62, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (32, 'Aromat Spice / Seasoning', 'Wine - Red, Mouton Cadet', 2, 'AREA', 7, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (33, 'Rice Paper', 'Sherry - Dry', 79, 'AREA', 67, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (34, 'Basil - Thai', 'Lid - Translucent, 3.5 And 6 Oz', 50, 'LENGTH', 47, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (35, 'Anchovy Paste - 56 G Tube', 'Lamb - Whole, Frozen', 62, 'AREA', 49, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (36, 'Bamboo Shoots - Sliced', 'Wine - Alsace Gewurztraminer', 98, 'LITRE', 44, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (37, 'Coffee - Dark Roast', 'Oil - Avocado', 58, 'LITRE', 73, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (38, 'Beef - Roasted, Cooked', 'Wine - Magnotta - Cab Sauv', 98, 'LITRE', 44, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (39, 'Banana - Green', 'Cranberries - Fresh', 58, 'AREA', 25, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (40, 'Nut - Pecan, Halves', 'Ice Cream Bar - Drumstick', 23, 'KG', 21, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (41, 'Jameson - Irish Whiskey', 'Clam - Cherrystone', 71, 'AREA', 78, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (42, 'Sauerkraut', 'Wine - Redchard Merritt', 14, 'AREA', 75, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (43, 'Vermouth - White, Cinzano', 'Bread - Wheat Baguette', 52, 'AREA', 87, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (44, 'Beets - Mini Golden', 'Wine - Prem Select Charddonany', 2, 'LENGTH', 78, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (45, 'Wine - Cave Springs Dry Riesling', 'Cookie - Oreo 100x2', 35, 'AREA', 38, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (46, 'Stock - Fish', 'Crush - Cream Soda', 7, 'LENGTH', 15, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (47, 'Danishes - Mini Raspberry', 'Dikon', 45, 'LENGTH', 39, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (48, 'Pea - Snow', 'Carbonated Water - Blackcherry', 39, 'LENGTH', 69, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (49, 'Pepper - White, Whole', 'Iced Tea Concentrate', 7, 'LENGTH', 29, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (50, 'Limes', 'Bread - Pita', 71, 'AREA', 41, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (51, 'Island Oasis - Ice Cream Mix', 'Shrimp - Black Tiger 8 - 12', 67, 'LITRE', 48, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (52, 'Jello - Assorted', 'Crab - Blue, Frozen', 34, 'KG', 85, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (53, 'Dr. Pepper - 355ml', 'Chicken - White Meat With Tender', 44, 'AREA', 70, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (54, 'Curry Powder', 'Lettuce - Lolla Rosa', 49, 'LENGTH', 53, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (55, 'Remy Red Berry Infusion', 'Onions - Pearl', 45, 'LENGTH', 84, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (56, 'Beef - Kindney, Whole', 'Beer - Steamwhistle', 32, 'AREA', 47, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (57, 'Rabbit - Frozen', 'Nut - Hazelnut, Ground, Natural', 1, 'AREA', 1, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (58, 'Salsify, Organic', 'Appetizer - Tarragon Chicken', 59, 'AREA', 34, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (59, 'Puree - Kiwi', 'Ecolab - Ster Bac', 75, 'LENGTH', 5, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (60, 'Cut Wakame - Hanawakaba', 'Milk 2% 500 Ml', 50, 'AREA', 100, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (61, 'Rice - Aborio', 'Island Oasis - Lemonade', 67, 'KG', 3, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (62, 'Beef Dry Aged Tenderloin Aaa', 'Butcher Twine 4r', 9, 'AREA', 95, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (63, 'Pork - Sausage, Medium', 'Soup - Campbells Chili', 57, 'KG', 97, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (64, 'Wine - Sake', 'Uniform Linen Charge', 92, 'AREA', 84, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (65, 'Beer - Heinekin', 'Foam Cup 6 Oz', 62, 'KG', 60, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (66, 'Drambuie', 'Mix - Cappucino Cocktail', 91, 'LENGTH', 81, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (67, 'Napkin Colour', 'Snapple Lemon Tea', 93, 'LENGTH', 71, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (68, 'Hersey Shakes', 'Shrimp - 16/20, Iqf, Shell On', 94, 'LENGTH', 43, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (69, 'Puree - Mocha', 'Canada Dry', 62, 'KG', 95, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (70, 'Puree - Mango', 'Cheese - Pied De Vents', 84, 'LENGTH', 25, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (71, 'Muffin Mix - Oatmeal', 'Apron', 3, 'LITRE', 87, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (72, 'Doilies - 5, Paper', 'Breadfruit', 74, 'AREA', 42, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (73, 'Ice Cream - Fudge Bars', 'Potatoes - Fingerling 4 Oz', 100, 'LENGTH', 18, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (74, 'The Pop Shoppe - Black Cherry', 'Amarula Cream', 45, 'AREA', 10, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (75, 'Curry Paste - Madras', 'Nut - Cashews, Whole, Raw', 88, 'KG', 34, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (76, 'Beef - Striploin', 'Phyllo Dough', 17, 'KG', 66, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (77, 'Wine - Savigny - Les - Beaune', 'Cocoa Powder - Dutched', 16, 'AREA', 46, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (78, 'Zucchini - Yellow', 'Sauce - Caesar Dressing', 56, 'LITRE', 42, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (79, 'Wine - Chablis 2003 Champs', 'Bread Base - Goodhearth', 20, 'LITRE', 23, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (80, 'Jicama', 'Containter - 3oz Microwave Rect.', 85, 'LENGTH', 60, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (81, 'Appetizer - Crab And Brie', 'Tilapia - Fillets', 66, 'AREA', 31, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (82, 'Squash - Guords', 'Browning Caramel Glace', 40, 'AREA', 14, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (83, 'Oil - Truffle, White', 'Pork - Inside', 82, 'LENGTH', 36, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (84, 'Pork - Sausage, Medium', 'Bread - French Stick', 94, 'AREA', 91, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (85, 'Beef - Short Loin', 'Wine - Riesling Alsace Ac 2001', 47, 'AREA', 53, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (86, 'Oil - Pumpkinseed', 'Veal - Round, Eye Of', 37, 'KG', 57, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (87, 'Cheese - Pont Couvert', 'Bread - Kimel Stick Poly', 30, 'AREA', 25, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (88, 'Chocolate - Unsweetened', 'Peach - Halves', 32, 'KG', 19, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (89, 'Container Clear 8 Oz', 'Wine - Conde De Valdemar', 33, 'LITRE', 64, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (90, 'Capicola - Hot', 'Wine - Baron De Rothschild', 17, 'AREA', 87, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (91, 'Bonito Flakes - Toku Katsuo', 'Anisette - Mcguiness', 72, 'LITRE', 78, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (92, 'Food Colouring - Green', 'Creme De Menthe Green', 78, 'KG', 33, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (93, 'Wine - White, Ej', 'Sea Bass - Fillets', 22, 'LENGTH', 99, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (94, 'Tea - Black Currant', 'Jerusalem Artichoke', 5, 'KG', 61, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (95, 'Sun - Dried Tomatoes', 'Beer - Camerons Cream Ale', 93, 'KG', 31, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (96, 'Muffin Mix - Corn Harvest', 'Wine - Cave Springs Dry Riesling', 31, 'LITRE', 92, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (97, 'Pasta - Orecchiette', 'Wine - Red, Antinori Santa', 22, 'LENGTH', 44, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (98, 'Cake - Sheet Strawberry', 'Irish Cream - Butterscotch', 7, 'AREA', 82, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (99, 'Sugar - Crumb', 'Wine - Zinfandel Rosenblum', 25, 'LITRE', 58, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (100, 'Cake - Mini Cheesecake', 'Mcguinness - Blue Curacao', 35, 'AREA', 30, 0);
