insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (3, 'Wine - Two Oceans Sauvignon', 'Wine - White, Concha Y Toro', 37, 'LITRE', 46, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (56, 'Bagel - Sesame Seed Presliced', 'Emulsifier', 93, 'LENGTH', 56, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (10, 'Wine - Red, Black Opal Shiraz', 'Soup - Campbells Beef Noodle', 37, 'KG', 7, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (22, 'Ham - Smoked, Bone - In', 'Beets - Golden', 98, 'LITRE', 99, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (75, 'Trout Rainbow Whole', 'Gloves - Goldtouch Disposable', 31, 'LITRE', 46, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (57, 'Tofu - Firm', 'Wine - Red, Wolf Blass, Yellow', 59, 'LITRE', 52, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (8, 'Beer - Molson Excel', 'Lid Coffee Cup 8oz Blk', 30, 'KG', 86, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (62, 'Nantucket Cranberry Juice', 'Vinegar - Balsamic, White', 57, 'AREA', 20, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (98, 'Wine - Pinot Grigio Collavini', 'Pastry - Trippleberry Muffin - Mini', 6, 'AREA', 47, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (41, 'Rum - Mount Gay Eclipes', 'Beans - Black Bean, Canned', 36, 'LITRE', 52, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (77, 'Beer - Maudite', 'Pineapple - Regular', 94, 'LENGTH', 74, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (79, 'Arizona - Plum Green Tea', 'Appetizer - Lobster Phyllo Roll', 51, 'KG', 9, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (28, 'Cocktail Napkin Blue', 'Cheese - Swiss Sliced', 20, 'KG', 79, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (37, 'Chinese Lemon Pork', 'Ecolab Digiclean Mild Fm', 48, 'AREA', 77, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (40, 'Hummus - Spread', 'Eel Fresh', 26, 'LENGTH', 54, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (2, 'Pasta - Shells, Medium, Dry', 'Appetizer - Sausage Rolls', 29, 'KG', 33, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (7, 'Beans - Yellow', 'Sesame Seed Black', 62, 'LITRE', 58, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (49, 'Artichokes - Knobless, White', 'Wine - Cave Springs Dry Riesling', 33, 'KG', 48, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (12, 'Gelatine Leaves - Envelopes', 'Pork - Bones', 53, 'LITRE', 39, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (35, 'Wine - Chardonnay South', 'Pepper - Cayenne', 1, 'AREA', 15, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (53, 'Instant Coffee', 'Fond - Neutral', 14, 'LENGTH', 23, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (51, 'Bandage - Finger Cots', 'Cream - 18%', 65, 'LITRE', 63, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (58, 'Bread - Bistro White', 'Dried Peach', 91, 'AREA', 50, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (49, 'Gelatine Leaves - Envelopes', 'Longan', 80, 'AREA', 24, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (70, 'Trueblue - Blueberry Cranberry', 'Crush - Orange, 355ml', 22, 'AREA', 45, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (54, 'Beer - Original Organic Lager', 'Kirsch - Schloss', 86, 'AREA', 96, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (61, 'Pie Shell - 9', 'Cake Slab', 16, 'LENGTH', 62, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (43, 'Wine - Malbec Trapiche Reserve', 'Clam Nectar', 10, 'LENGTH', 41, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (43, 'Steampan - Lid For Half Size', 'Lid - Translucent, 3.5 And 6 Oz', 5, 'AREA', 17, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (43, 'Napkin - Dinner, White', 'Table Cloth 90x90 Colour', 98, 'KG', 80, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (86, 'Tea - Black Currant', 'Pasta - Linguini, Dry', 23, 'AREA', 79, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (28, 'Buttons', 'Mushroom - Chanterelle Frozen', 38, 'KG', 90, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (28, 'Eggplant - Regular', 'Gatorade - Xfactor Berry', 30, 'AREA', 57, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (82, 'Beef - Short Ribs', 'Cookie - Oreo 100x2', 49, 'KG', 84, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (7, 'Lettuce - Mini Greens, Whole', 'Crab - Dungeness, Whole', 25, 'KG', 94, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (31, 'Vermouth - White, Cinzano', 'Nantucket - 518ml', 34, 'KG', 12, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (63, 'Beef - Rib Roast, Capless', 'Jerusalem Artichoke', 84, 'KG', 71, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (32, 'Bread - Roll, Canadian Dinner', 'Bar Nature Valley', 41, 'LITRE', 19, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (52, 'Vinegar - Tarragon', 'Squid - U 5', 58, 'AREA', 81, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (80, 'Mortadella', 'Cheese - Mascarpone', 82, 'KG', 63, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (63, 'Mix Pina Colada', 'Nestea - Ice Tea, Diet', 17, 'AREA', 88, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (55, 'Pork - Hock And Feet Attached', 'Wanton Wrap', 94, 'LENGTH', 93, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (24, 'Vodka - Hot, Lnferno', 'Gooseberry', 81, 'LITRE', 14, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (78, 'Pineapple - Golden', 'Kiwi Gold Zespri', 21, 'LENGTH', 54, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (100, 'Chocolate - Milk', 'Bread - Raisin', 22, 'KG', 49, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (8, 'Olives - Kalamata', 'Oven Mitt - 13 Inch', 7, 'AREA', 41, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (30, 'Bouq All Italian - Primerba', 'Island Oasis - Peach Daiquiri', 39, 'LITRE', 69, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (77, 'Beef - Ox Tongue, Pickled', 'Wine - Champagne Brut Veuve', 59, 'LENGTH', 63, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (43, 'Yogurt - Peach, 175 Gr', 'Bread - White, Sliced', 74, 'LENGTH', 5, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (75, 'Tea - Apple Green Tea', 'Pastry - Banana Tea Loaf', 72, 'LENGTH', 9, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (27, 'Cake - French Pear Tart', 'Octopus', 66, 'AREA', 9, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (72, 'Bread - Crusty Italian Poly', 'Rice Paper', 32, 'LENGTH', 53, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (87, 'Ice Cream Bar - Hagen Daz', 'Towel Multifold', 88, 'AREA', 37, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (21, 'Sachet', 'Nantucket Cranberry Juice', 23, 'KG', 1, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (88, 'Soup Knorr Chili With Beans', 'Pepper - White, Whole', 40, 'KG', 2, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (75, 'Soup Knorr Chili With Beans', 'Zucchini - Yellow', 38, 'LITRE', 42, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (31, 'Jameson Irish Whiskey', 'Chicken - Soup Base', 2, 'AREA', 80, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (6, 'Wine - Magnotta - Cab Franc', 'Juice - Apple, 1.36l', 91, 'LITRE', 24, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (3, 'Juice - Ocean Spray Cranberry', 'Veal - Striploin', 51, 'LENGTH', 49, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (81, 'Guinea Fowl', 'Blouse / Shirt / Sweater', 16, 'AREA', 62, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (47, 'Clementine', 'Soup - Canadian Pea, Dry Mix', 36, 'KG', 34, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (56, 'Veal - Leg', 'Brandy - Bar', 4, 'LITRE', 99, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (3, 'Lobster - Cooked', 'Bread - Pumpernickel', 63, 'LITRE', 97, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (77, 'Shiratamako - Rice Flour', 'Cake Sheet Combo Party Pack', 82, 'LITRE', 7, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (75, 'Quail - Jumbo', 'Chevril', 35, 'LITRE', 46, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (86, 'Walkers Special Old Whiskey', 'Mushroom - Morels, Dry', 7, 'LENGTH', 3, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (53, 'Stock - Veal, White', 'Flour Dark Rye', 54, 'LENGTH', 8, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (78, 'Nantucket - Kiwi Berry Cktl.', 'Bread - Burger', 19, 'AREA', 86, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (76, 'Ginger - Ground', 'Raisin - Golden', 86, 'KG', 77, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (100, 'Flower - Leather Leaf Fern', 'Wine - Sicilia Igt Nero Avola', 32, 'LITRE', 42, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (91, 'Syrup - Monin - Blue Curacao', 'Stock - Chicken, White', 71, 'KG', 16, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (96, 'Bread - White, Sliced', 'Wine - Taylors Reserve', 25, 'KG', 56, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (18, 'Cheese - Cambozola', 'Onions Granulated', 30, 'AREA', 74, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (19, 'Lemon Tarts', 'Caviar - Salmon', 13, 'KG', 22, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (66, 'Mushroom - Shitake, Fresh', 'Cheese - Gorgonzola', 3, 'AREA', 81, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (84, 'Coffee - 10oz Cup 92961', 'Chips Potato All Dressed - 43g', 95, 'AREA', 83, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (85, 'Muffin Orange Individual', 'Latex Rubber Gloves Size 9', 64, 'LENGTH', 77, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (25, 'Wine - Prosecco Valdobienne', 'Dawn Professionl Pot And Pan', 81, 'KG', 80, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (79, 'Wine - White, Schroder And Schyl', 'Sea Bass - Fillets', 3, 'LITRE', 31, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (59, 'Foam Tray S2', 'Cocktail Napkin Blue', 94, 'AREA', 8, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (62, 'Halibut - Steaks', 'Muffin Carrot - Individual', 81, 'LITRE', 62, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (7, 'Dip - Tapenade', 'Chilli Paste, Ginger Garlic', 71, 'LENGTH', 41, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (82, 'Pork - Suckling Pig', 'Island Oasis - Wildberry', 22, 'AREA', 53, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (85, 'Tilapia - Fillets', 'Beer - Fruli', 66, 'KG', 97, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (21, 'Pepper - Roasted Red', 'Wine - Lamancha Do Crianza', 48, 'LITRE', 80, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (60, 'Wine - Taylors Reserve', 'Cocoa Powder - Dutched', 42, 'LENGTH', 24, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (80, 'Coffee - Colombian, Portioned', 'Oil - Macadamia', 37, 'KG', 33, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (39, 'Scallops - 10/20', 'Ham - Procutinni', 2, 'LENGTH', 6, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (68, 'Icecream - Dibs', 'Momiji Oroshi Chili Sauce', 75, 'KG', 26, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (84, 'Hickory Smoke, Liquid', 'Pheasants - Whole', 11, 'KG', 83, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (74, 'Beer - Camerons Auburn', 'Flavouring - Raspberry', 85, 'LENGTH', 8, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (67, 'Muffin - Mix - Bran And Maple 15l', 'Wine - Barossa Valley Estate', 67, 'LENGTH', 6, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (45, 'Fish - Artic Char, Cold Smoked', 'Compound - Strawberry', 23, 'LENGTH', 7, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (41, 'Fish - Scallops, Cold Smoked', 'Turkey - Ground. Lean', 86, 'LENGTH', 46, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (42, 'Mustard - Individual Pkg', 'Vol Au Vents', 52, 'LENGTH', 33, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (84, 'Longos - Chicken Curried', 'Pork - Loin, Bone - In', 10, 'LENGTH', 20, 1);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (20, 'Venison - Ground', 'Cup - Translucent 7 Oz Clear', 66, 'AREA', 30, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (96, 'Foil Wrap', 'Pastry - Banana Tea Loaf', 33, 'LENGTH', 81, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (95, 'Nut - Walnut, Chopped', 'Beans - Yellow', 31, 'KG', 79, 0);
insert into Products (PID, PNAME, PDESC, PSIZE, UOM, AISLE, LIVE) values (81, 'Chocolate - Milk, Callets', 'Wine - Duboeuf Beaujolais', 12, 'LENGTH', 80, 0);
